name: Hello World CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Static Code Analysis
      uses: actions/codeql-action
    - name: Request Code Review
      uses: actions/request-review
      with:
        reviewers: octocat
    - name: Build and Test
      run: mvn clean install
    - name: Unit Test
      run: mvn test
    - name: Functional Test
      uses: actions/selenium-action
